CREATE TABLE STUDENT(
    SSN INT NOT NULL,
    ID INT NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    MIDDLENAME VARCHAR(20),
    LASTNAME VARCHAR(20) NOT NULL,
    RESIDENCY VARCHAR(10) NOT NULL,
    ENROLLMENT VARCHAR(10) NOT NULL,
    CONSTRAINT PK_STD PRIMARY KEY(ID)
);


CREATE TABLE DEPT(
    DEPT_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DEPT PRIMARY KEY(DEPT_NAME)
);

CREATE TABLE FACULTY(
	FACULTY_NAME VARCHAR(50) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	DEPT VARCHAR(20) NOT NULL references DEPT(DEPT_NAME),
	CONSTRAINT PK_FACULTY PRIMARY KEY(FACULTY_NAME)
);

CREATE TABLE DEGREE(
	DEGREE_NAME VARCHAR(20) NOT NULL,
	DEGREE_TYPE VARCHAR(20) NOT NULL,
	UNITS INT NOT NULL,
	DEPT VARCHAR(20) NOT NULL references DEPT(DEPT_NAME),
	CONSTRAINT PK_DEGREE PRIMARY KEY(DEGREE_NAME,DEGREE_TYPE)
);

CREATE TABLE CATEGORY(
    CATE_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CATE PRIMARY KEY(CATE_NAME)
);

CREATE TABLE CATEGORY_DEGREE(
	CATE_NAME VARCHAR(20) NOT NULL references CATEGORY(CATE_NAME),
	MIN_UNIT INT NOT NULL,
    GPA REAL NOT NULL,
    MAJOR VARCHAR(20) NOT NULL,
    DEGREE_TYPE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CATEDEGREE PRIMARY KEY(CATE_NAME,MAJOR,DEGREE_TYPE),
    FOREIGN KEY (MAJOR,DEGREE_TYPE) references DEGREE(DEGREE_NAME,DEGREE_TYPE)
);



CREATE TABLE COURSE(
    COURSE_ID VARCHAR(20) NOT NULL,
    COURSE_NAME VARCHAR(50) NOT NULL,
    MIN_UNIT INT NOT NULL,
    MAX_UNIT INT NOT NULL,
    DEPT VARCHAR(10) NOT NULL references DEPT(DEPT_NAME),
    GRADE_OPTION VARCHAR(10) NOT NULL,
    LAB_REQUIRED VARCHAR(10) NOT NULL,
    INSTRUCTOR_CONSENT VARCHAR(10) NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL references CATEGORY(CATE_NAME),
    CONSTRAINT PK_COURSE PRIMARY KEY(COURSE_ID)
);


CREATE TABLE CONCENTRATION(
    CON_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CONNAME PRIMARY KEY(CON_NAME)
);

CREATE TABLE CONCENTRATION_LIST(
	CON_NAME VARCHAR(20) NOT NULL references CONCENTRATION(CON_NAME),
	COURSE VARCHAR(20) NOT NULL references COURSE(COURSE_ID)
);


CREATE TABLE CONCENTRATION_DEGREE(
    CON_NAME VARCHAR(20) NOT NULL references CONCENTRATION(CON_NAME),
    MIN_UNIT INT NOT NULL,
    DEPT VARCHAR(20) NOT NULL,
    DEGREE_TYPE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CONDEGREE PRIMARY KEY(CON_NAME,DEPT,DEGREE_TYPE),
    FOREIGN KEY (DEPT,DEGREE_TYPE) references DEGREE(DEGREE_NAME,DEGREE_TYPE)
);


CREATE TABLE UNDERGRAD(
	PID INT NOT NULL references STUDENT(ID),
	COLLEGE VARCHAR(20) NOT NULL,
	MAJOR VARCHAR(20) NOT NULL,
	MINOR VARCHAR(20) NOT NULL,
	MAJOR_TYPE VARCHAR(20) NOT NULL,
	CONSTRAINT PK_UNDERGRAD PRIMARY KEY(PID),
	FOREIGN KEY (MAJOR,MAJOR_TYPE) references DEGREE(DEGREE_NAME,DEGREE_TYPE)
);


CREATE TABLE GRAD(
	PID INT NOT NULL references STUDENT(ID),
	DEPT VARCHAR(20) NOT NULL references DEPT(DEPT_NAME),
	PROGRAM VARCHAR(20) NOT NULL,
	NUM_OF_COMMITTEE INT NOT NULL,
    ADVISOR VARCHAR(20) NOT NULL references FACULTY(FACULTY_NAME),
	CONSTRAINT PK_GRAD PRIMARY KEY(PID)
);



CREATE TABLE PREREQ(
    COURSE_ID VARCHAR(20) NOT NULL references COURSE(COURSE_ID),
    PREREQ_ID VARCHAR(20) NOT NULL references COURSE(COURSE_ID)
);


CREATE TABLE OWNED_DEGREE(
	PID INT NOT NULL references STUDENT(ID),
	DEGREE VARCHAR(50) NOT NULL,
	UNIVERSITY VARCHAR(50) NOT NULL,
  CONSTRAINT PK_OWNED PRIMARY KEY(PID, DEGREE)
);



CREATE TABLE ATTENDANCE(
	PID INT NOT NULL references STUDENT(ID),
	START_QUARTER VARCHAR(20) NOT NULL,
	START_YEAR INT NOT NULL,
	END_QUARTER VARCHAR(20) NOT NULL,
	END_YEAR INT NOT NULL,
  CONSTRAINT PK_ATTEND PRIMARY KEY(PID, START_QUARTER, START_YEAR)
);

CREATE TABLE PROBATION(
	PID INT NOT NULL references STUDENT(ID),
    CASE_ID INT NOT NULL,
	START_QUARTER VARCHAR(20) NOT NULL,
	START_YEAR INT NOT NULL,
	END_QUARTER VARCHAR(20) NOT NULL,
	END_YEAR INT NOT NULL,
	REASON VARCHAR(50) NOT NULL,
  CONSTRAINT PK_CASEID PRIMARY KEY(CASE_ID)
);


CREATE TABLE THESIS_COMMITTEE(
	PID INT NOT NULL references GRAD(PID),
	FACULTY VARCHAR(50) NOT NULL references FACULTY(FACULTY_NAME),
  CONSTRAINT PK_COMMITTE PRIMARY KEY(PID, FACULTY)
);


CREATE TABLE CLASS(
    CLASS_ID INT NOT NULL,
    COURSE_ID VARCHAR(20) NOT NULL references COURSE(COURSE_ID),
    INSTRUCTOR VARCHAR(20) NOT NULL references FACULTY(FACULTY_NAME),
	ENROLLMENT_LIMIT INT NOT NULL,
    QUARTER VARCHAR(20) NOT NULL,
    YEAR INT NOT NULL,
    CONSTRAINT PK_CLASS PRIMARY KEY(CLASS_ID)
);


CREATE TABLE ENROLLED_LIST(
	CLASS_ID INT NOT NULL references CLASS(CLASS_ID),
	COURSE_ID VARCHAR(20) references COURSE(COURSE_ID),
	PID INT NOT NULL references STUDENT(ID),
	GRADE_OPTION VARCHAR(20) NOT NULL,
	GRADE_RECEIVED VARCHAR(20) NOT NULL,
	UNIT INT NOT NULL,
	QUARTER VARCHAR(20) NOT NULL,
	YEAR INT NOT NULL,
	CONSTRAINT PK_ENROLLED PRIMARY KEY(CLASS_ID)
);

CREATE TABLE ENROLL_CURRENT(
	CLASS_ID INT NOT NULL references CLASS(CLASS_ID),
	COURSE_ID VARCHAR(20) references COURSE(COURSE_ID),
	PID INT NOT NULL references STUDENT(ID),
	GRADE_OPTION VARCHAR(20) NOT NULL,
	UNIT INT NOT NULL,
	CONSTRAINT PK_ENROLLCURRENT PRIMARY KEY(CLASS_ID)
);

CREATE TABLE WAIT_LIST(
	CLASS_ID INT NOT NULL references CLASS(CLASS_ID),
	PID INT NOT NULL references STUDENT(ID),
	GRADE_OPTION VARCHAR(10) NOT NULL,
	UNIT INT NOT NULL,
	CONSTRAINT PK_WL PRIMARY KEY(CLASS_ID)
);

CREATE TABLE WEEKLING_MEETINGS(
	CLASS_ID INT NOT NULL references CLASS(CLASS_ID),
    REQUIRED VARCHAR(20) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
	DATE VARCHAR(20) NOT NULL,
	TIME VARCHAR(20) NOT NULL,
	ROOM VARCHAR(20) NOT NULL,
  CONSTRAINT PK_WM PRIMARY KEY(CLASS_ID, DATE, TIME, ROOM)
);

CREATE TABLE REVIEW_SESSIONS(
	CLASS_ID INT NOT NULL references CLASS(CLASS_ID),
	DATE VARCHAR(20) NOT NULL,
	TIME VARCHAR(20) NOT NULL,
	ROOM VARCHAR(20) NOT NULL
);
